name: learn-github-actions
on: [push]
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build a.out
        run: gcc hello.c

      - name: Save dist
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./a.out

  test_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: load dist
        uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run test
        run: ./test.sh
