name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen"
  check-bats-version-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is a computetr"
