name: learn-github-actions
on: [push]
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build_job"
      - uses: actions/checkout@v2
      - run: gcc hello.c

  test_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test_job"
          ./test.sh
