name: learn-github-actions
on: [push]
jobs:
  test_job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test_job_1, steps_1"
      - uses: actions/checkout@v2
      - run: |
          ls -al
          cd .github/workflows/
          ls -al
  test_job_2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test_job_2, steps_1"
